### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by makemota** [yu-li/TCMonoDepth#10]
Upon running 
`python demo.py --model large --resume ./weights/_ckpt.pt.tar --input ./videos --output ./output --resize_size 384`
got an error:
**Output & Stacktrace:**

```
F:\Depth_estimation\TCMonoDepth-main>python demo.py --model large --resume ./weights/_ckpt.pt.tar --input ./videos --output ./output --resize_size 384
Run Video Depth Sample
Initialize
Device: cuda
Creating model...
Loading model from ./weights/_ckpt.pt.tar
Loading model done...
Traceback (most recent call last):
  File "demo.py", line 148, in <module>
    run(args)
  File "demo.py", line 76, in run
    args.resize_size[0],  #width
TypeError: 'int' object is not subscriptable
```

**Comment by semel1** [comment]
Managed to successfully run by edit two lines of code:
```
78            args.resize_size{0},  #width   to  args.resize_size,  #width
79            args.resize_size{1},  #height  to  args.resize_size,  #height
```

**Comment by SU1997** [comment]
after that, i got a new error:


File "demo.py", line 76
    args.resize_size{0},  #width
                    ^
SyntaxError: invalid syntax
